///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_git_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("64652b2f-ccf9-4858-a587-eb5049a1e303")]
    public partial class rx_git_projRepository : RepoGenBaseFolder
    {
        static rx_git_projRepository instance = new rx_git_projRepository();
        rx_git_projRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        rx_git_projRepositoryFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the rx_git_projRepository element repository.
        /// </summary>
        [RepositoryFolder("64652b2f-ccf9-4858-a587-eb5049a1e303")]
        public static rx_git_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_git_projRepository() 
            : base("rx_git_projRepository", "/", null, 0, false, "64652b2f-ccf9-4858-a587-eb5049a1e303", ".\\RepositoryImages\\rx_git_projRepository64652b2f.rximgres")
        {
            _keypromptform = new rx_git_projRepositoryFolders.KeyPromptFormAppFolder(this);
            _mainform = new rx_git_projRepositoryFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("64652b2f-ccf9-4858-a587-eb5049a1e303")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("ecdb047a-c8cb-4b69-a870-814d9142d037")]
        public virtual rx_git_projRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("4ab20fab-7830-4810-a781-b4a8a74decde")]
        public virtual rx_git_projRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class rx_git_projRepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("ecdb047a-c8cb-4b69-a870-814d9142d037")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mbtncancelInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "ecdb047a-c8cb-4b69-a870-814d9142d037", "")
            {
                _mbtncancelInfo = new RepoItemInfo(this, "MBtnCancel", "button[@controlname='m_btnCancel']", 30000, null, "1210487f-a929-47ce-b9cf-1efed63599f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecdb047a-c8cb-4b69-a870-814d9142d037")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecdb047a-c8cb-4b69-a870-814d9142d037")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBtnCancel item.
            /// </summary>
            [RepositoryItem("1210487f-a929-47ce-b9cf-1efed63599f2")]
            public virtual Ranorex.Button MBtnCancel
            {
                get
                {
                    return _mbtncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnCancel item info.
            /// </summary>
            [RepositoryItemInfo("1210487f-a929-47ce-b9cf-1efed63599f2")]
            public virtual RepoItemInfo MBtnCancelInfo
            {
                get
                {
                    return _mbtncancelInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("4ab20fab-7830-4810-a781-b4a8a74decde")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "4ab20fab-7830-4810-a781-b4a8a74decde", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@accessiblename='File']", 30000, null, "77c44710-d732-4437-882b-9a4f9ad56310");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "0c976ae9-b751-41d4-ac4e-beb956c744aa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ab20fab-7830-4810-a781-b4a8a74decde")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ab20fab-7830-4810-a781-b4a8a74decde")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("77c44710-d732-4437-882b-9a4f9ad56310")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("77c44710-d732-4437-882b-9a4f9ad56310")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("0c976ae9-b751-41d4-ac4e-beb956c744aa")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("0c976ae9-b751-41d4-ac4e-beb956c744aa")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}